### ISSUE TITLE
图片后有文字会导致转发失败

### ISSUE THREAD

**Issue by mxlt02** [IllTamer/infinite-bot-3-expansion#3]
![image](https://user-images.githubusercontent.com/57489136/185755574-043a26e6-e178-4c03-9e59-41de5c5d8ca5.png)

**Comment by IllTamer** [comment]
已修复 https://github.com/IllTamer/infinite-bot-3-expansion/commit/9cf00d748edff1a9ca11ce765d996320fd91470f#diff-c415b274d26835655e030efa085e093fb9123d5b9e5851882e32c250bf560b8e

请下载最新的发行版本
