### ISSUE TITLE
[功能请求] 更改绑定的使用方式

### ISSUE THREAD

**Issue by Baikele** [IllTamer/infinite-bot-3-expansion#7]
吧在游戏内发送 确认绑定QQ号改成，点击文字就可以确认绑定，这样，会不会很方便

**Comment by Baikele** [comment]
更新一下，

加群的那个建议添加一个是否是当前群ingroup

**Comment by IllTamer** [comment]
> 更新一下，
> 
> 加群的那个建议添加一个是否是当前群ingroup

请问这点是什么意思，是机器人在未管理的群中触发了入群欢迎消息吗？实现上触发入群欢迎时是会检测群组是否在groups中的，这点在功能添加之初就没变动过

**Comment by Baikele** [comment]
> 现上触发入群欢

是的
