### ISSUE TITLE
View-manager未能正常工作

### ISSUE THREAD

**Issue by GLDYM** [IllTamer/infinite-bot-3-expansion#8]
### 问题描述
1.开启expand-chat后，未在群内显示相应信息，并在控制台报错。
2.游戏内无法显示图片，控制台未报错

### 服务端版本
git-Purpur-1905 (MC: 1.19.3)

### 插件版本列表
Plugins (22): AllMusic, Boom, Citizens, CoreProtect, DiscordSRV, dynmap, Essentials, EssentialsChat, EssentialsSpawn, FartherViewDistance, FreedomChat, GSit, InfiniteBot3*, InteractiveChat, InteractiveChatDiscordSrvAddon, LuckPerms, PlaceholderAPI, ProtocolLib, spark, TAB, Vault, WorldEdit

InfiniteBot3  3.1.7
chat-manager 2.0
view-manage 2.0

DiscordSRV  1.26.0
InteractiveChat 4.2.5.6
InteractiveChatDiscordSrvAddon 4.2.5.6

更多详细信息
[latest.log](https://github.com/IllTamer/infinite-bot-3-expansion/files/10680469/latest.log)

**Comment by IllTamer** [comment]
本问题已修复，是view-manager及chat-manager未适配新版ica所致，解决方法如下

1. 待本体3.2.0发布后重新下载本体与配套附属
2. 加群获取临时升级版附属，待本体升级后再升级配套附属
